services:
  - type: web
    name: whiteflows-elite
    runtime: python
    plan: standard # Required for persistent disks
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_PATH
        value: /var/lib/whiteflows/whiteflows.db
      - key: LOG_FILE_PATH
        value: /var/lib/whiteflows/server_logs.txt
      - key: PORT
        value: 8001
      - key: ADMIN_PASSWORD
        sync: false
      - key: GMAIL_SENDER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: GMAIL_RECEIVER
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
      - key: BREVO_LOGIN
        sync: false
      - key: BACKUP_RECEIVER_EMAIL
        sync: false
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: whiteflows-data
      mountPath: /var/lib/whiteflows
      sizeGB: 1
