name = "whiteflows-elite"
main = "worker.py"
compatibility_date = "2024-12-01"
compatibility_flags = ["python_workers"]

[vars]
GMAIL_SENDER = "your-email@gmail.com"
GMAIL_RECEIVER = "recipient-email@gmail.com"
BREVO_API_KEY = "your-brevo-api-key"
RESEND_API_KEY = "your-resend-api-key"
ADMIN_PASSWORD = "whiteflows2026"

# Assets (Frontend)
[assets]
directory = "./"
binding = "ASSETS"
